### ISSUE TITLE
Switch to ES6 and .vue component files

### ISSUE THREAD

**Issue by Aerilius** [Aerilius/sketchup-attribute-inspector#1]
The current approach ([multiline strings and inline style blocks](https://github.com/Aerilius/sketchup-attribute-inspector/blob/e4a5560543697079505214f6d9c89bf034585257/src/ae_attribute_inspector/js/components.js#L61)) is a clever solution to facilitate hacking for collaborators directly on the production code without previous knowledge about build tools. 

But I think the better readability (no `\n\`) and no need to care about supported JavaScript features rather outweigh it. Therefore one could switch to npm/babel/ES6 and .vue component files.

**Comment by Aerilius** [comment]
See branch  [es6-port](https://github.com/Aerilius/sketchup-attribute-inspector/tree/es6-port)

**Comment by Macavirus** [comment]
es6-port branch has been deleted, recommend to close this issue
